# Generated by Django 4.2.6 on 2023-10-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_treemenu_id_alter_treemenucategory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemenu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='app.treemenucategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='treemenu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treemenucategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
